name: Automated Tests

on:
  pull_request:
    branches: [main]

jobs:
  jest:
    services:
      postgres:
        image: postgres:16
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASS }}
    name: Jest Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/hydrogen"

      - run: npm ci

      - run: npm test
