# .github/workflows/ci.yml
name: Automated Test

on:
  pull_request:
    branches: [main]

jobs:
  jest:
    name: Jest Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests

      - uses: actions/setup-no@v4
        with:
          node-version: "lts/hydrogen"
      - run: npm ci
      - run: npm test
